# espanso match file

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:

  - trigger: ":date:"
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ":jdate:"
    replace: "{{jdate}}"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%d-%m"
