# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.chat/configuration/

[servers.liberachat]
nickname = "unixGEEK"
nick_password_file = "~/.config/halloy/password/libera"
server = "irc.libera.chat"
channels = ["#halloy", "#archlinux"]

# [proxy.socks5]
# host = "127.0.0.1"
# port = 9050
