# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.chat/configuration/


theme = "Catppuccin Mocha"

[servers.liberachat]
nickname = "unixGEEK"
server = "irc.libera.chat"
channels = ["#halloy", "#archlinux"]

