# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.chat/configuration/

[servers.liberachat]
nickname = "unixGEEK"
server = "irc.libera.chat"
channels = ["#halloy"]

[proxy.socks5]
host = "127.0.0.1"
port = 9050
